apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd.yaml
  # - argocd-ha.yaml
  # - ingress.yaml

# Setting some configurations for our Argo install
configMapGenerator:
  - name: argocd-cm
    behavior: replace
    literals:
      # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/
      - application.resourceTrackingMethod=annotation
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#existing-oidc-provider
      # - url=https://argocd.company.net
      # Default is 3mn, for performance we set 30mn and rely on hooks from Gitlab to trigger syncs
      - timeout.reconciliation=1800s
      # Enable Helm support in Kustomize
      - kustomize.buildOptions=--enable-helm
      # Enable ProgressiveSync for ApplicationSets
      - applicationsetcontroller.enable.progressive.syncs=true
    options:
      disableNameSuffixHash: true
